<?php
// $Id$

/**
 * @file
 *
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 * Felix Delattre <felix.delattre@erdfisch.de>
 */

include_once('omniauth_relying.features.inc');

/**
 * Implement hook_menu().
 */
function omniauth_relying_menu() {
  $items = array();
  // Move log in page to login/direct. See how openid_sso_menu_alter() replaces
  // log in.
  $items['user/login'] = array(
    'title' => 'Log in',
    'page callback' => 'omniauth_relying_user_page',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );
  $items['user/register'] = array(
    'title' => 'Create new account',
    'page callback' => 'omniauth_relying_user_register_page',
    'access callback' => 'user_register_access',
    'type' => MENU_CALLBACK,
  );
  $items['user/password'] = array(
    'title' => 'Request new password',
    'page callback' => 'omniauth_relying_user_password_page',
    'page arguments' => array('user_pass'),
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implement HOOK_menu_alter().
 */
function omniauth_relying_menu_alter(&$items) {
  if (!user_access('administer openid client ax')) {
    $items['user/%user/openid']['access callback'] = FALSE;
  }
}

/**
 * Custom menu callback for user/page.
 */
function omniauth_relying_user_page() {
  global $user;
  if ($user->uid) {
    return user_page();
  }
  return openid_sso_request();
}

/**
 * Custom menu callback for user/register.
 */
function omniauth_relying_user_register_page() {
  $provider = variable_get('openid_sso_provider', array());
  drupal_goto(url($provider['url'] . 'user/register', array('absolute' => TRUE)));
}

/**
 * Custom menu callback for user/password.
 */
function omniauth_relying_user_password_page() {
  $provider = variable_get('openid_sso_provider', array());
  drupal_goto(url($provider['url'] . 'user/password', array('absolute' => TRUE)));
}

/**
 * Implement HOOK_form_FORM_ID_alter().
 */
function omniauth_relying_form_profile_node_form_alter(&$form, &$form_state) {
  if (!user_access('administer nodes')) {
    $form['title']['#type'] = 'value';
    $form['body_field']['#type'] = 'value';
  }
}

/**
 * Implement HOOK_form_FORM_ID_alter().
 */
function omniauth_relying_form_user_profile_form_alter(&$form, &$form_state) {
  $provider = variable_get('openid_sso_provider', array());

  $form['account']['name']['#disabled'] = TRUE;
  $form['account']['name']['#value'] = $form['account']['name']['#default_value'];
  $form['account']['name']['#description'] = t('Please visit the !sso_name to change your username and password', array(
    '!sso_name' => l(t('Single-Sign-On-Provider'), $provider['url']))
  );

  $form['account']['mail']['#disabled'] = TRUE;
  $form['account']['mail']['#value'] = $form['account']['mail']['#default_value'];
  $form['account']['mail']['#description'] = t('Please visit the !sso_name to change your email address', array(
    '!sso_name' => l(t('Single-Sign-On-Provider'), $provider['url']))
  );

  unset($form['account']['pass']);
}

